name: task_manager
description: Um aplicativo Flutter para gerenciamento de tarefas
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  uuid: ^4.2.1
  intl: ^0.19.0
  flutter_staggered_animations: ^1.1.1
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  sensors_plus: ^4.0.2
  vibration: ^1.8.4
  geolocator: ^10.1.0
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
